### ISSUE TITLE
Alumni Members don't get any cool flags

### ISSUE THREAD

**Issue by sgreene570** [ComputerScienceHouse/packet#173] opened 2019-09-04 21:42 UTC
When viewing a packet, Active Members have cool labels when applicable. 
![Screenshot](https://user-images.githubusercontent.com/17414243/64293738-40482200-cf3b-11e9-9f88-e1bd080e0cca.png)
However, alumni members do not get any of these cool labels (even if they should).
![Screenshot (1)](https://user-images.githubusercontent.com/17414243/64293760-4b9b4d80-cf3b-11e9-9919-ad04757323c8.png)

**Comment by devinmatte** [comment] 2019-09-09 17:40
Duplicate of #138

**Closed by devinmatte** 2019-09-09 17:40 UTC
